### ISSUE TITLE
License Issues

### ISSUE THREAD

**Issue by cg7033** [cfHxqA/Mission-Chief.Bot#9]
Hey all,

It might just be me being thick, but where do you find the license key for Missionchief? Furthermore, what is your Discord server? All your links are invalid.

Thanks

**Comment by cfHxqA** [comment]
Regards @cg7033,

you are warmly invited to visit us: https://discord.gg/9vDwzk


Just write in a Discord channel or contact me directly on the server. ;-) 🤓
